version: "3.8"
services:
  api:
    image: aintproud/nest
    build:
      dockerfile: Dockerfile 
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:3000/test
      PORT: 3000
    ports: 
      - "2000:3000"
  postgres:
    image: postgres:latest
    ports:
    - "3000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test



