version: "3.8"
services:
  api:
    image: nest
    build:
      dockerfile: Dockerfile 
      context: .
    depends_on:
      - postgres
    ports: 
      - "2000:4000"
  postgres:
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres



